In [1]:
import numpy as np

In [51]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]

In [99]:
new = np.array ([list1,list2])

In [80]:
new.reshape(1,10)

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]])

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones([1,4])

array([[1., 1., 1., 1.]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.random.randn(4,4)

array([[-0.59761237,  1.01257245, -0.84022588, -0.10265426],
       [-0.4271626 ,  1.46966849, -0.34730762,  1.48011967],
       [-0.95061113, -2.78423817, -1.01709598,  1.21255492],
       [ 0.24094274, -0.45862797,  1.41586233,  0.08465758]])

In [42]:
np.random.rand(10)

array([0.78656567, 0.39577906, 0.94489535, 0.81844687, 0.34395718,
       0.1673536 , 0.65976853, 0.9329045 , 0.89373127, 0.72555021])

In [61]:
np.random.randint(10)

9

In [75]:
new.argmax()

np.int64(9)

In [82]:
new.dtype

dtype('int64')

In [104]:
new

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [103]:
new[new > 5] * 2

array([12, 14, 16, 18])

In [105]:
np.sqrt(new)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [106]:
np.exp(new)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [107]:
np.sum(new , axis = 0)

array([ 6,  8, 10, 12, 14])

In [108]:
np.sum(new , axis = 1)

array([15, 35])

In [109]:
pwd

'C:\\Users\\Ank3t'